# Generated by Django 4.1.4 on 2023-06-15 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel_controle', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
