# Generated by Django 4.1.4 on 2024-03-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('painel_controle', '0002_delete_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, null=True, verbose_name='Nome Curso')),
                ('tipo_curso', models.CharField(choices=[('Técnico', 'Técnico'), ('Graduação', 'Graduação')], max_length=40)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
