# Generated by Django 5.0.3 on 2024-03-23 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, null=True, verbose_name='Tipo de Solicitação')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição da Solicitação')),
                ('arquivo', models.ImageField(upload_to="static/solicitacoes/arquivo/<class 'django.contrib.auth.models.User'>/")),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes.tiposolicitacao')),
            ],
        ),
    ]
