# Generated by Django 5.0.3 on 2024-03-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('aprovado', 'Aprovado'), ('em_analise', 'Em Analise'), ('negado', 'Negado'), ('cancelado', 'Cancelado')], default='em_analise', max_length=20, verbose_name='Status da Solicitação'),
        ),
    ]
