# Generated by Django 5.0.3 on 2024-03-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0002_solicitacao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='arquivo',
            field=models.FileField(upload_to="static/solicitacoes/arquivo/<class 'django.contrib.auth.models.User'>/"),
        ),
    ]
